#
# Makefile for host Kernel running with stage 2 translation
#
#obj-y += AbstractMachine.o
obj-y += MemBlock.o
obj-y += PageIndex.o
obj-y += PageMgmt.o
obj-y += PTAlloc.o
obj-y += PTWalk.o
obj-y += NPTWalk.o
obj-y += NPTOps.o
obj-y += MemAux.o
obj-y += MemOps.o
obj-y += VMPower.o
obj-y += BootCore.o
obj-y += BootOps.o
#obj-y += BootAux.o
obj-y += Helper.o
obj-y += VCPUOpsAux.o
obj-y += VCPUOps.o
obj-y += vs.o
obj-y += hs.o
##obj-y += mmap.o
obj-y += csr-sr.o
#obj-y += hacl-20/
obj-y += PlicOps.o
obj-y += PlicAux.o
obj-y += PlicCore.o
obj-y += PlicCoreAux.o
obj-y += PlicRaw.o
obj-y += MemHandler.o
#obj-y += MmioPTAlloc.o
#obj-y += MmioPTWalk.o
#obj-y += MmioSPTWalk.o
#obj-y += MmioSPTOps.o
obj-y += TrapDispatcher.o
obj-y += FaultHandler.o
