#ifndef __RISCV_STAGE2_PGTABLE__
#define __RISCV_STAGE2_PGTABLE__

#define STAGE2_INIT_PGTABLE_LEVELS     3

//use the following for multi-vm
#define STAGE2_HOST_POOL_SIZE	SZ_2M * 100
#define STAGE2_VM_POOL_SIZE	SZ_2M * 4
#define STAGE2_NORM_PAGES_SIZE 	STAGE2_VM_POOL_SIZE * 64
//use the following for multi-vm
//#define STAGE2_CORE_PAGES_SIZE         SZ_2M * 80
#define STAGE2_CORE_PAGES_SIZE 	SZ_2M * 128
#define STAGE2_PAGES_SIZE      	STAGE2_CORE_PAGES_SIZE + STAGE2_HOST_POOL_SIZE + STAGE2_NORM_PAGES_SIZE
#define SMMU_PAGES_SIZE  	SZ_2M * 24
#define STAGE2_TMP_PAGES_SIZE  	0
#define CORE_DATA_SIZE		PAGE_SIZE * (PAGE_SIZE * 24)

#define STAGE2_NUM_CORE_PAGES  	(STAGE2_CORE_PAGES_SIZE / PAGE_SIZE)
#define STAGE2_NUM_TMP_PAGES   	(STAGE2_TMP_PAGES_SIZE / PAGE_SIZE)

#endif /* __RISCV_STAGE2_PGTABLE__ */
